org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx1G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false

appName=NzLeagueCore
projectVersion=1.0.0

graalHelperVersion=2.0.1
enableGraalNative=false

shadowJarPluginVersion=9.3.2
jlinkPluginVersion=3.2.1

gdxVersion=1.14.2

lombokVersion=1.18.42
junitVersion=5.10.0
gdxUnitVersion=1.6

okHttpVersion=5.3.2
gsonVersion=2.11.0
jacksonCoreVersion=3.1.1

lolClientVersion=1.2.3

daggerVersion=2.57.2

slf4jVersion=2.0.17
log4j2Version=2.25.3

jctoolsVersion=4.0.5
fastUtilVersion=5.0.9

jnativehookVersion=2.2.2
lmaxVersion=3.4.4
oshiVersion=6.9.2
commonsIOVersion=2.21.0

reflectionsVersion=0.10.2

gst1Version=1.4.0
jnaVersion=5.18.1
